### ISSUE TITLE
program is unresponsive (for minutes) while slow ion sets calculate

### ISSUE THREAD

**Issue by saglag** [swharden/LJPcalc#14]
Performed a calculation. Swapped sulfate ion used in calculation and app became unresponsive.

**Comment by swharden** [comment]
Yeah, due to the algorithm sometimes the program gets stuck in a near-infinite (minutes) calculation.  I'll track this fix as part of #9, where the anticipated fix is adding an "abort" button for stuck calculations, as well as notes about how to correct it.

Adding a long ion set is annoying currently if it crashes, so you can make use of the ion set save/load buttons in the mean time
